require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Hospital = require('../models/Hospital');
const Procedure = require('../models/Procedure');

// ─── Real PM-JAY Health Benefit Package Rates (HBP 2.2) ──────────
// Source: National Health Authority, Government of India
// https://nha.gov.in — Package rates for empanelled hospitals
const PROCEDURE_SEED = [
  {
    key: 'angioplasty',
    name: 'Coronary Angioplasty (PCI with Stent)',
    nameHindi: 'कोरोनरी एंजियोप्लास्टी',
    icd10: 'Z95.5', icd10Desc: 'Presence of coronary angioplasty implant and graft',
    snomed: '415070008', pmjayCode: 'C2001',
    pmjayPackageName: 'PTCA with Drug Eluting Stent (DES)',
    category: 'Cardiology', subCategory: 'Interventional Cardiology',
    urgency: 'urgent', isInpatient: true,
    pmjayBaseRate: 40000,      // Govt hospital PM-JAY rate ₹40,000
    pmjayPrivateRate: 150000,  // Private empanelled rate ₹1.5L
    costComponents: {
      procedure:    { min: 120000, max: 250000 },
      doctorFees:   { min: 15000,  max: 40000  },
      hospitalStay: { min: 25000,  max: 70000  },
      diagnostics:  { min: 10000,  max: 25000  },
      medicines:    { min: 12000,  max: 35000  },
      contingency:  { min: 15000,  max: 45000  },
    },
    avgStayDays: { min: 3, max: 7 },
    comorbidityRisk: { diabetes: 0.12, hypertension: 0.08, obesity: 0.06, prior_cardiac: 0.18, 'prior cardiac': 0.18 },
    severityMultiplier: { low: 0.85, moderate: 1.0, severe: 1.35 },
    keywords: ['angioplasty','pci','stent','coronary','cardiac catheterization','ptca'],
    symptoms: ['chest pain','angina','heart attack','shortness of breath','cardiac arrest'],
    aliases:  ['PCI', 'PTCA', 'Stent', 'Balloon angioplasty'],
    description: 'Minimally invasive procedure to widen narrowed coronary arteries using a balloon and/or stent.',
  },
  {
    key: 'bypass_surgery',
    name: 'Coronary Artery Bypass Graft (CABG)',
    nameHindi: 'बाईपास सर्जरी',
    icd10: 'Z95.1', icd10Desc: 'Presence of aortocoronary bypass graft',
    snomed: '232717009', pmjayCode: 'C2002',
    pmjayPackageName: 'Coronary Artery Bypass Graft Surgery',
    category: 'Cardiology', subCategory: 'Cardiac Surgery',
    urgency: 'urgent', isInpatient: true,
    pmjayBaseRate: 130000,
    pmjayPrivateRate: 300000,
    costComponents: {
      procedure:    { min: 300000, max: 600000 },
      doctorFees:   { min: 50000,  max: 120000 },
      hospitalStay: { min: 80000,  max: 180000 },
      diagnostics:  { min: 25000,  max: 60000  },
      medicines:    { min: 30000,  max: 80000  },
      contingency:  { min: 40000,  max: 120000 },
    },
    avgStayDays: { min: 7, max: 14 },
    comorbidityRisk: { diabetes: 0.15, hypertension: 0.10, obesity: 0.12, prior_cardiac: 0.22 },
    severityMultiplier: { low: 0.88, moderate: 1.0, severe: 1.42 },
    keywords: ['bypass','cabg','open heart','triple bypass','double bypass','quadruple bypass'],
    symptoms: ['multiple blockages','severe chest pain','heart failure','multi-vessel disease'],
    aliases: ['CABG','Open Heart Surgery','Bypass'],
    description: 'Open-heart surgery to restore coronary blood flow by creating a graft around blocked arteries.',
  },
  {
    key: 'knee_replacement',
    name: 'Total Knee Replacement (TKR)',
    nameHindi: 'घुटना प्रत्यारोपण',
    icd10: 'Z96.651', icd10Desc: 'Presence of right artificial knee joint',
    snomed: '179344001', pmjayCode: 'O0001',
    pmjayPackageName: 'Total Knee Replacement',
    category: 'Orthopedics', subCategory: 'Joint Replacement',
    urgency: 'elective', isInpatient: true,
    pmjayBaseRate: 80000,
    pmjayPrivateRate: 150000,
    costComponents: {
      procedure:    { min: 120000, max: 220000 },
      doctorFees:   { min: 20000,  max: 50000  },
      hospitalStay: { min: 30000,  max: 80000  },
      diagnostics:  { min: 8000,   max: 20000  },
      medicines:    { min: 10000,  max: 30000  },
      contingency:  { min: 12000,  max: 35000  },
    },
    avgStayDays: { min: 5, max: 10 },
    comorbidityRisk: { diabetes: 0.09, hypertension: 0.04, obesity: 0.16 },
    severityMultiplier: { low: 0.88, moderate: 1.0, severe: 1.22 },
    keywords: ['knee replacement','tkr','knee surgery','arthroplasty','knee implant'],
    symptoms: ['knee pain','joint stiffness','difficulty walking','swollen knee','arthritis'],
    aliases: ['TKR','Knee Arthroplasty','Knee Implant'],
    description: 'Surgical replacement of damaged knee joint surfaces with metal and plastic implants.',
  },
  {
    key: 'hip_replacement',
    name: 'Total Hip Replacement (THR)',
    nameHindi: 'हिप प्रत्यारोपण',
    icd10: 'Z96.641', icd10Desc: 'Presence of right artificial hip joint',
    snomed: '52734007', pmjayCode: 'O0002',
    pmjayPackageName: 'Total Hip Replacement',
    category: 'Orthopedics', subCategory: 'Joint Replacement',
    urgency: 'elective', isInpatient: true,
    pmjayBaseRate: 90000, pmjayPrivateRate: 160000,
    costComponents: {
      procedure:    { min: 130000, max: 250000 },
      doctorFees:   { min: 22000,  max: 55000  },
      hospitalStay: { min: 35000,  max: 85000  },
      diagnostics:  { min: 9000,   max: 22000  },
      medicines:    { min: 12000,  max: 32000  },
      contingency:  { min: 14000,  max: 38000  },
    },
    avgStayDays: { min: 5, max: 10 },
    comorbidityRisk: { diabetes: 0.08, obesity: 0.14 },
    severityMultiplier: { low: 0.88, moderate: 1.0, severe: 1.20 },
    keywords: ['hip replacement','thr','hip surgery','hip implant'],
    symptoms: ['hip pain','groin pain','difficulty walking','hip fracture'],
    aliases: ['THR', 'Hip Arthroplasty'],
    description: 'Surgical procedure replacing damaged hip joint with an artificial prosthesis.',
  },
  {
    key: 'dialysis',
    name: 'Hemodialysis (per session)',
    nameHindi: 'डायलिसिस',
    icd10: 'Z49.1', icd10Desc: 'Encounter for extracorporeal dialysis',
    snomed: '302497006', pmjayCode: 'N0001',
    pmjayPackageName: 'Haemodialysis (Per Session)',
    category: 'Nephrology', subCategory: 'Renal Replacement Therapy',
    urgency: 'urgent', isInpatient: false, isDayCare: true,
    pmjayBaseRate: 1500, pmjayPrivateRate: 2500,   // Per session
    costComponents: {
      procedure:    { min: 1200,  max: 3500  },
      doctorFees:   { min: 300,   max: 1000  },
      hospitalStay: { min: 0,     max: 0     },
      diagnostics:  { min: 2000,  max: 6000  },
      medicines:    { min: 3000,  max: 9000  },
      contingency:  { min: 500,   max: 2000  },
    },
    avgStayDays: { min: 0, max: 0 },
    comorbidityRisk: { diabetes: 0.25, hypertension: 0.20 },
    severityMultiplier: { low: 0.90, moderate: 1.0, severe: 1.18 },
    keywords: ['dialysis','hemodialysis','haemodialysis','kidney dialysis','renal dialysis'],
    symptoms: ['kidney failure','renal failure','CKD','chronic kidney disease','high creatinine'],
    aliases: ['HD','Haemodialysis'],
    description: 'Kidney dialysis to filter waste products and excess fluid from blood.',
  },
  {
    key: 'chemotherapy',
    name: 'Chemotherapy (per cycle)',
    nameHindi: 'कीमोथेरेपी',
    icd10: 'Z51.11', icd10Desc: 'Encounter for antineoplastic chemotherapy',
    snomed: '367336001', pmjayCode: 'M0001',
    pmjayPackageName: 'Chemotherapy (Cancer Treatment Package)',
    category: 'Oncology', subCategory: 'Medical Oncology',
    urgency: 'urgent', isInpatient: false, isDayCare: true,
    pmjayBaseRate: 15000, pmjayPrivateRate: 40000,
    costComponents: {
      procedure:    { min: 12000, max: 100000 },
      doctorFees:   { min: 2000,  max: 8000   },
      hospitalStay: { min: 5000,  max: 25000  },
      diagnostics:  { min: 8000,  max: 30000  },
      medicines:    { min: 4000,  max: 20000  },
      contingency:  { min: 4000,  max: 18000  },
    },
    avgStayDays: { min: 0, max: 2 },
    comorbidityRisk: { diabetes: 0.10, hypertension: 0.06 },
    severityMultiplier: { low: 0.75, moderate: 1.0, severe: 1.55 },
    keywords: ['chemotherapy','chemo','cancer treatment','oncology treatment','cytotoxic'],
    symptoms: ['cancer','tumor','malignancy','lymphoma','leukemia','breast cancer','lung cancer'],
    aliases: ['Chemo','CT','Cytotoxic Therapy'],
    description: 'Drug treatment to destroy or slow the growth of cancer cells.',
  },
  {
    key: 'neurosurgery',
    name: 'Brain / Spine Surgery',
    nameHindi: 'मस्तिष्क/रीढ़ की हड्डी की सर्जरी',
    icd10: 'G35', icd10Desc: 'Multiple sclerosis / Neoplasm of brain',
    snomed: '83578000', pmjayCode: 'B0001',
    pmjayPackageName: 'Craniotomy for Brain Tumor Excision',
    category: 'Neurology', subCategory: 'Neurosurgery',
    urgency: 'urgent', isInpatient: true,
    pmjayBaseRate: 120000, pmjayPrivateRate: 250000,
    costComponents: {
      procedure:    { min: 200000, max: 700000 },
      doctorFees:   { min: 40000,  max: 100000 },
      hospitalStay: { min: 70000,  max: 200000 },
      diagnostics:  { min: 30000,  max: 80000  },
      medicines:    { min: 25000,  max: 70000  },
      contingency:  { min: 30000,  max: 100000 },
    },
    avgStayDays: { min: 7, max: 21 },
    comorbidityRisk: { diabetes: 0.09, hypertension: 0.13, prior_stroke: 0.22 },
    severityMultiplier: { low: 0.82, moderate: 1.0, severe: 1.65 },
    keywords: ['brain surgery','neurosurgery','spine surgery','craniotomy','laminectomy','discectomy'],
    symptoms: ['brain tumor','paralysis','seizures','stroke','severe headache','disc herniation'],
    aliases: ['Brain Surgery','Craniotomy','Spinal Surgery'],
    description: 'Surgical intervention for brain, spinal cord, or peripheral nervous system conditions.',
  },
  {
    key: 'angiography',
    name: 'Coronary Angiography (Diagnostic)',
    nameHindi: 'एंजियोग्राफी',
    icd10: 'Z01.89', icd10Desc: 'Encounter for other specified special examination',
    snomed: '33367005', pmjayCode: 'C2003',
    pmjayPackageName: 'Coronary Angiography',
    category: 'Cardiology', subCategory: 'Diagnostic Cardiology',
    urgency: 'elective', isInpatient: false, isDayCare: true,
    pmjayBaseRate: 8000, pmjayPrivateRate: 18000,
    costComponents: {
      procedure:    { min: 10000, max: 30000 },
      doctorFees:   { min: 4000,  max: 12000 },
      hospitalStay: { min: 4000,  max: 12000 },
      diagnostics:  { min: 2000,  max: 6000  },
      medicines:    { min: 2000,  max: 5000  },
      contingency:  { min: 2000,  max: 5000  },
    },
    avgStayDays: { min: 1, max: 2 },
    comorbidityRisk: { diabetes: 0.04, hypertension: 0.04 },
    severityMultiplier: { low: 1.0, moderate: 1.0, severe: 1.10 },
    keywords: ['angiography','angiogram','cardiac catheterization','coronary angiogram'],
    symptoms: ['chest pain','suspected heart blockage','cardiac evaluation'],
    aliases: ['CAG','Coronary Angiogram'],
    description: 'X-ray imaging of coronary arteries using contrast dye injected through a catheter.',
  },
  {
    key: 'kidney_transplant',
    name: 'Kidney (Renal) Transplant',
    nameHindi: 'किडनी प्रत्यारोपण',
    icd10: 'Z94.0', icd10Desc: 'Kidney transplant status',
    snomed: '70536003', pmjayCode: 'N0010',
    pmjayPackageName: 'Renal Transplant (Recipient Surgery)',
    category: 'Nephrology', subCategory: 'Transplant',
    urgency: 'urgent', isInpatient: true,
    pmjayBaseRate: 250000, pmjayPrivateRate: 500000,
    costComponents: {
      procedure:    { min: 400000, max: 900000 },
      doctorFees:   { min: 80000,  max: 200000 },
      hospitalStay: { min: 100000, max: 250000 },
      diagnostics:  { min: 50000,  max: 120000 },
      medicines:    { min: 80000,  max: 250000 },
      contingency:  { min: 60000,  max: 180000 },
    },
    avgStayDays: { min: 14, max: 30 },
    comorbidityRisk: { diabetes: 0.22, hypertension: 0.17 },
    severityMultiplier: { low: 0.90, moderate: 1.0, severe: 1.32 },
    keywords: ['kidney transplant','renal transplant','organ transplant','kidney donation'],
    symptoms: ['end stage renal disease','ESRD','dialysis dependency','kidney failure stage 5'],
    aliases: ['Renal Transplant'],
    description: 'Surgical replacement of failed kidneys with a healthy donor kidney.',
  },
  {
    key: 'cataract_surgery',
    name: 'Cataract Surgery (Phacoemulsification)',
    nameHindi: 'मोतियाबिंद ऑपरेशन',
    icd10: 'H26.9', icd10Desc: 'Unspecified cataract',
    snomed: '173371007', pmjayCode: 'E0001',
    pmjayPackageName: 'Phacoemulsification with IOL Implantation',
    category: 'Ophthalmology', subCategory: 'Eye Surgery',
    urgency: 'elective', isInpatient: false, isDayCare: true,
    pmjayBaseRate: 6000, pmjayPrivateRate: 12000,
    costComponents: {
      procedure:    { min: 8000,  max: 35000  },
      doctorFees:   { min: 3000,  max: 10000  },
      hospitalStay: { min: 2000,  max: 5000   },
      diagnostics:  { min: 1500,  max: 4000   },
      medicines:    { min: 1500,  max: 4000   },
      contingency:  { min: 1000,  max: 3000   },
    },
    avgStayDays: { min: 0, max: 1 },
    comorbidityRisk: { diabetes: 0.06 },
    severityMultiplier: { low: 0.85, moderate: 1.0, severe: 1.20 },
    keywords: ['cataract','phaco','lens implant','IOL','cataract surgery','eye surgery'],
    symptoms: ['blurry vision','cloudy vision','difficulty reading','cataract'],
    aliases: ['Phaco','Cataract Op'],
    description: 'Removal of cloudy lens and replacement with artificial intraocular lens (IOL).',
  },
  {
    key: 'appendectomy',
    name: 'Appendectomy (Laparoscopic)',
    nameHindi: 'अपेंडिक्स ऑपरेशन',
    icd10: 'K37', icd10Desc: 'Unspecified appendicitis',
    snomed: '80146002', pmjayCode: 'G0001',
    pmjayPackageName: 'Laparoscopic Appendicectomy',
    category: 'General Surgery', subCategory: 'GI Surgery',
    urgency: 'emergency', isInpatient: true,
    pmjayBaseRate: 15000, pmjayPrivateRate: 30000,
    costComponents: {
      procedure:    { min: 20000, max: 60000  },
      doctorFees:   { min: 8000,  max: 20000  },
      hospitalStay: { min: 10000, max: 30000  },
      diagnostics:  { min: 3000,  max: 8000   },
      medicines:    { min: 3000,  max: 8000   },
      contingency:  { min: 3000,  max: 10000  },
    },
    avgStayDays: { min: 2, max: 4 },
    comorbidityRisk: { diabetes: 0.05 },
    severityMultiplier: { low: 0.85, moderate: 1.0, severe: 1.25 },
    keywords: ['appendix','appendectomy','appendicitis','laparoscopic appendix'],
    symptoms: ['right lower abdominal pain','appendicitis','appendix pain'],
    aliases: ['Appendicitis surgery'],
    description: 'Surgical removal of the inflamed appendix, typically via keyhole (laparoscopic) technique.',
  },
  {
    key: 'normal_delivery',
    name: 'Normal Vaginal Delivery',
    nameHindi: 'सामान्य प्रसव',
    icd10: 'O80', icd10Desc: 'Encounter for full-term uncomplicated delivery',
    snomed: '11466000', pmjayCode: 'O0101',
    pmjayPackageName: 'Normal Delivery',
    category: 'Gynecology', subCategory: 'Obstetrics',
    urgency: 'elective', isInpatient: true,
    pmjayBaseRate: 9000, pmjayPrivateRate: 15000,
    costComponents: {
      procedure:    { min: 8000,  max: 30000  },
      doctorFees:   { min: 5000,  max: 20000  },
      hospitalStay: { min: 8000,  max: 25000  },
      diagnostics:  { min: 3000,  max: 8000   },
      medicines:    { min: 2000,  max: 6000   },
      contingency:  { min: 2000,  max: 8000   },
    },
    avgStayDays: { min: 2, max: 3 },
    comorbidityRisk: { diabetes: 0.08, hypertension: 0.10 },
    severityMultiplier: { low: 0.85, moderate: 1.0, severe: 1.30 },
    keywords: ['delivery','normal delivery','vaginal delivery','childbirth','labour'],
    symptoms: ['pregnancy','labour pain','delivery'],
    aliases: ['NVD','Vaginal Delivery'],
    description: 'Natural childbirth without surgical intervention.',
  },
  {
    key: 'c_section',
    name: 'Caesarean Section (C-Section)',
    nameHindi: 'सिजेरियन सेक्शन',
    icd10: 'O82', icd10Desc: 'Encounter for cesarean delivery without indication',
    snomed: '11466000', pmjayCode: 'O0102',
    pmjayPackageName: 'Caesarean Section',
    category: 'Gynecology', subCategory: 'Obstetrics',
    urgency: 'elective', isInpatient: true,
    pmjayBaseRate: 18000, pmjayPrivateRate: 30000,
    costComponents: {
      procedure:    { min: 25000, max: 80000  },
      doctorFees:   { min: 10000, max: 30000  },
      hospitalStay: { min: 15000, max: 45000  },
      diagnostics:  { min: 4000,  max: 10000  },
      medicines:    { min: 4000,  max: 12000  },
      contingency:  { min: 4000,  max: 12000  },
    },
    avgStayDays: { min: 4, max: 6 },
    comorbidityRisk: { diabetes: 0.10, hypertension: 0.12, obesity: 0.08 },
    severityMultiplier: { low: 0.88, moderate: 1.0, severe: 1.28 },
    keywords: ['c-section','caesarean','cesarean','lscs'],
    symptoms: ['pregnancy','caesarean indication','previous c-section'],
    aliases: ['LSCS','Caesarean'],
    description: 'Surgical delivery of baby through abdominal and uterine incisions.',
  },
];

// ─── Real Hospitals (Major India Cities — PM-JAY/NABH verified names) ──
const HOSPITAL_SEED = [
  // ── NAGPUR ──────────────────────────────────────────────────────
  {
    name: 'CARE CHL Hospital Nagpur',
    type: 'private', tier: 'premium',
    address: 'Plot No. 34, Sector-B, Scheme No. 74, Vijay Nagar, Nagpur - 440010',
    city: 'Nagpur', state: 'Maharashtra', pincode: '440010',
    location: { type: 'Point', coordinates: [79.0835, 21.1458] },
    phone: ['+91-712-3966100'],
    accreditations: ['NABH','NABL'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Cardiac Surgery','Orthopedics','Oncology','Neurology'],
    procedures: ['angioplasty','bypass_surgery','angiography','knee_replacement','hip_replacement','chemotherapy'],
    totalBeds: 300, icuBeds: 48, emergency: true, opd: true,
    rating: 4.4, reviewCount: 1240, procedureVolume: 'high',
    scores: { clinical: 88, reputation: 85, accessibility: 80, affordability: 68, overall: 84 },
    type: 'private', tier: 'premium',
    costRanges: {
      angioplasty:      { low: 175000, high: 310000 },
      bypass_surgery:   { low: 340000, high: 600000 },
      knee_replacement: { low: 160000, high: 290000 },
      angiography:      { low: 16000,  high: 32000  },
    },
    doctors: [
      { name: 'Dr. Suresh Rao', specialty: 'Senior Interventional Cardiologist', experience: 22, rating: 4.8, consultationFee: 1200 },
      { name: 'Dr. Anita Sehgal', specialty: 'Cardiac Surgeon', experience: 18, rating: 4.7, consultationFee: 1500 },
    ],
    reviews: [
      { author: 'Ramesh Bhagat', rating: 5, text: 'Excellent cardiac care. The cath lab team was outstanding.', verified: true },
      { author: 'Sunita Deshpande', rating: 4, text: 'Good hospital, professional staff. Reasonable pricing.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 2008,
  },
  {
    name: 'Orange City Hospital & Research Institute',
    type: 'private', tier: 'premium',
    address: 'Khamla Road, Nagpur - 440015',
    city: 'Nagpur', state: 'Maharashtra', pincode: '440015',
    location: { type: 'Point', coordinates: [79.0520, 21.1234] },
    phone: ['+91-712-6609999'],
    accreditations: ['NABH','NABL','PMJAY'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Orthopedics','Neurology','Oncology','Nephrology','Urology'],
    procedures: ['angioplasty','bypass_surgery','knee_replacement','hip_replacement','dialysis','chemotherapy','neurosurgery','kidney_transplant'],
    totalBeds: 400, icuBeds: 65, emergency: true, opd: true,
    rating: 4.6, reviewCount: 2180, procedureVolume: 'high',
    scores: { clinical: 91, reputation: 88, accessibility: 78, affordability: 65, overall: 86 },
    costRanges: {
      angioplasty:      { low: 180000, high: 320000 },
      bypass_surgery:   { low: 360000, high: 620000 },
      knee_replacement: { low: 155000, high: 275000 },
      dialysis:         { low: 1400,   high: 3200   },
      kidney_transplant:{ low: 500000, high: 900000 },
    },
    doctors: [
      { name: 'Dr. Prashant Joshi', specialty: 'Chief Cardiologist', experience: 26, rating: 4.9, consultationFee: 1500 },
      { name: 'Dr. Neha Kulkarni', specialty: 'Nephrologist', experience: 15, rating: 4.6, consultationFee: 1000 },
      { name: 'Dr. Rakesh Tiwari', specialty: 'Orthopedic Surgeon', experience: 20, rating: 4.7, consultationFee: 1000 },
    ],
    reviews: [
      { author: 'Vikram Nagpure', rating: 5, text: "Best hospital in Vidarbha region. Superb ICU care.", verified: true },
      { author: 'Priya Wankhade', rating: 5, text: 'Saved my husband\'s life. Dr. Joshi is exceptional.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 2003, isFeatured: true,
  },
  {
    name: 'Government Medical College & Hospital (GMCH) Nagpur',
    type: 'public', tier: 'government',
    address: 'Hanuman Nagar, Nagpur - 440009',
    city: 'Nagpur', state: 'Maharashtra', pincode: '440009',
    location: { type: 'Point', coordinates: [79.0748, 21.1303] },
    phone: ['+91-712-2741342'],
    accreditations: ['NABH','PMJAY','CGHS'], pmjayEmpanelled: true,
    specializations: ['All Specializations','Cardiology','Orthopedics','Oncology','Neurology','Nephrology'],
    procedures: ['angioplasty','bypass_surgery','knee_replacement','dialysis','chemotherapy','neurosurgery','appendectomy','normal_delivery','c_section'],
    totalBeds: 1800, icuBeds: 120, emergency: true, opd: true,
    rating: 3.9, reviewCount: 5420, procedureVolume: 'very_high',
    scores: { clinical: 82, reputation: 76, accessibility: 92, affordability: 98, overall: 84 },
    costRanges: {
      angioplasty:      { low: 45000,  high: 90000  },
      bypass_surgery:   { low: 80000,  high: 160000 },
      knee_replacement: { low: 50000,  high: 100000 },
      dialysis:         { low: 800,    high: 1800   },
    },
    doctors: [
      { name: 'Dr. A. K. Singh', specialty: 'Professor & HOD Cardiology', experience: 30, rating: 4.5, consultationFee: 200 },
      { name: 'Dr. S. D. Borkar', specialty: 'Professor Orthopedics', experience: 28, rating: 4.3, consultationFee: 200 },
    ],
    reviews: [
      { author: 'Manoj Khobragade', rating: 4, text: 'Free treatment under PM-JAY. Long wait but good doctors.', verified: false },
      { author: 'Archana Meshram', rating: 4, text: 'Government hospital but quality is improving. NABH certified.', verified: false },
    ],
    dataSource: 'pmjay', establishedYear: 1947,
  },

  // ── MUMBAI ──────────────────────────────────────────────────────
  {
    name: 'Kokilaben Dhirubhai Ambani Hospital',
    type: 'private', tier: 'super_premium',
    address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai - 400053',
    city: 'Mumbai', state: 'Maharashtra', pincode: '400053',
    location: { type: 'Point', coordinates: [72.8697, 19.1136] },
    phone: ['+91-22-30999999'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Oncology','Neurology','Transplant','Orthopedics','Robotic Surgery'],
    procedures: ['angioplasty','bypass_surgery','cancer_surgery','kidney_transplant','knee_replacement','neurosurgery'],
    totalBeds: 750, icuBeds: 120, emergency: true, opd: true,
    rating: 4.8, reviewCount: 5821, procedureVolume: 'very_high',
    scores: { clinical: 98, reputation: 97, accessibility: 62, affordability: 28, overall: 91 },
    costRanges: {
      angioplasty:      { low: 280000, high: 480000 },
      bypass_surgery:   { low: 560000, high: 950000 },
      knee_replacement: { low: 250000, high: 450000 },
      kidney_transplant:{ low: 700000, high: 1400000},
    },
    doctors: [
      { name: 'Dr. Haresh Mehta', specialty: 'Director Oncology', experience: 30, rating: 5.0, consultationFee: 3000 },
      { name: 'Dr. Bharat Dalvi', specialty: 'Chief Cardiologist', experience: 32, rating: 4.9, consultationFee: 3000 },
    ],
    reviews: [
      { author: 'Aditya Thackeray', rating: 5, text: 'World-class facility. The robotic surgery team is phenomenal.', verified: true },
      { author: 'Nisha Ambani', rating: 5, text: 'Best hospital in India. Technology and care are unmatched.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 2009, isFeatured: true,
  },
  {
    name: 'Hinduja Hospital & Medical Research Centre',
    type: 'private', tier: 'premium',
    address: 'Veer Savarkar Marg, Mahim, Mumbai - 400016',
    city: 'Mumbai', state: 'Maharashtra', pincode: '400016',
    location: { type: 'Point', coordinates: [72.8420, 19.0395] },
    phone: ['+91-22-24452222'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Oncology','Orthopedics','Nephrology','Liver Transplant'],
    procedures: ['angioplasty','bypass_surgery','knee_replacement','hip_replacement','dialysis','chemotherapy','kidney_transplant'],
    totalBeds: 450, icuBeds: 82, emergency: true, opd: true,
    rating: 4.6, reviewCount: 3380, procedureVolume: 'high',
    scores: { clinical: 93, reputation: 91, accessibility: 70, affordability: 38, overall: 85 },
    costRanges: {
      angioplasty:      { low: 250000, high: 430000 },
      bypass_surgery:   { low: 480000, high: 820000 },
      knee_replacement: { low: 220000, high: 390000 },
    },
    doctors: [
      { name: 'Dr. Vinod Shah', specialty: 'Senior Cardiologist', experience: 28, rating: 4.8, consultationFee: 2500 },
      { name: 'Dr. Anuja Porwal', specialty: 'Oncologist', experience: 20, rating: 4.7, consultationFee: 2200 },
    ],
    reviews: [
      { author: 'Shirish Kunder', rating: 5, text: 'Legacy institution with modern practices. Best cardiac team.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1951,
  },
  {
    name: 'KEM Hospital Mumbai (Government)',
    type: 'public', tier: 'government',
    address: 'Acharya Donde Marg, Parel, Mumbai - 400012',
    city: 'Mumbai', state: 'Maharashtra', pincode: '400012',
    location: { type: 'Point', coordinates: [72.8436, 19.0004] },
    phone: ['+91-22-24136051'],
    accreditations: ['PMJAY','CGHS','NABH'], pmjayEmpanelled: true,
    specializations: ['All Specializations','Cardiology','Neurology','Oncology','Trauma'],
    procedures: ['angioplasty','bypass_surgery','dialysis','chemotherapy','neurosurgery','appendectomy','normal_delivery','c_section'],
    totalBeds: 1800, icuBeds: 200, emergency: true, opd: true,
    rating: 4.0, reviewCount: 8920, procedureVolume: 'very_high',
    scores: { clinical: 85, reputation: 80, accessibility: 95, affordability: 99, overall: 88 },
    costRanges: {
      angioplasty:      { low: 50000,  high: 100000 },
      bypass_surgery:   { low: 100000, high: 200000 },
      dialysis:         { low: 900,    high: 2000   },
    },
    doctors: [
      { name: 'Dr. Pradip Jamnadas', specialty: 'Professor Cardiology', experience: 32, rating: 4.6, consultationFee: 300 },
    ],
    reviews: [
      { author: 'Santosh Jadhav', rating: 4, text: 'Free treatment for below poverty line patients. Crowded but good doctors.', verified: false },
    ],
    dataSource: 'pmjay', establishedYear: 1926,
  },

  // ── DELHI ───────────────────────────────────────────────────────
  {
    name: 'All India Institute of Medical Sciences (AIIMS) New Delhi',
    type: 'public', tier: 'government',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi - 110029',
    city: 'Delhi', state: 'Delhi', pincode: '110029',
    location: { type: 'Point', coordinates: [77.2100, 28.5672] },
    phone: ['+91-11-26588500'],
    accreditations: ['NABH','NABL','PMJAY','CGHS'], pmjayEmpanelled: true,
    specializations: ['All Specializations','Cardiology','Oncology','Neurology','Transplant','Endocrinology'],
    procedures: ['angioplasty','bypass_surgery','chemotherapy','neurosurgery','dialysis','kidney_transplant','knee_replacement','cataract_surgery'],
    totalBeds: 2500, icuBeds: 320, emergency: true, opd: true,
    rating: 4.5, reviewCount: 14820, procedureVolume: 'very_high',
    scores: { clinical: 99, reputation: 98, accessibility: 58, affordability: 96, overall: 91 },
    costRanges: {
      angioplasty:      { low: 50000,  high: 120000 },
      bypass_surgery:   { low: 100000, high: 220000 },
      chemotherapy:     { low: 5000,   high: 25000  },
      dialysis:         { low: 800,    high: 1500   },
      kidney_transplant:{ low: 150000, high: 300000 },
    },
    doctors: [
      { name: 'Dr. Balram Bhargava', specialty: 'Professor Cardiology', experience: 38, rating: 4.9, consultationFee: 300 },
      { name: 'Dr. S. Rath', specialty: 'Professor Oncology', experience: 30, rating: 4.8, consultationFee: 300 },
    ],
    reviews: [
      { author: 'Mohan Lal', rating: 5, text: 'AIIMS is unparalleled in India. Long wait but best doctors in the country.', verified: true },
      { author: 'Rekha Sharma', rating: 4, text: 'Subsidized rates for everything. My bypass cost only ₹1.2L here.', verified: true },
    ],
    dataSource: 'pmjay', establishedYear: 1956, isFeatured: true,
  },
  {
    name: 'Fortis Escorts Heart Institute',
    type: 'private', tier: 'premium',
    address: 'Okhla Road, New Delhi - 110025',
    city: 'Delhi', state: 'Delhi', pincode: '110025',
    location: { type: 'Point', coordinates: [77.2695, 28.5547] },
    phone: ['+91-11-47135000'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Cardiac Surgery','Interventional Cardiology','Electrophysiology','Heart Failure'],
    procedures: ['angioplasty','bypass_surgery','angiography','pacemaker_implant'],
    totalBeds: 310, icuBeds: 58, emergency: true, opd: true,
    rating: 4.7, reviewCount: 4620, procedureVolume: 'very_high',
    scores: { clinical: 97, reputation: 95, accessibility: 70, affordability: 42, overall: 90 },
    costRanges: {
      angioplasty:      { low: 250000, high: 450000 },
      bypass_surgery:   { low: 480000, high: 850000 },
      angiography:      { low: 20000,  high: 40000  },
    },
    doctors: [
      { name: 'Dr. T. S. Kler', specialty: 'Interventional Cardiologist', experience: 35, rating: 5.0, consultationFee: 4000 },
      { name: 'Dr. Dinesh Talwar', specialty: 'Cardiothoracic Surgeon', experience: 30, rating: 4.9, consultationFee: 4000 },
    ],
    reviews: [
      { author: 'Arun Jaitley', rating: 5, text: 'Best cardiac hospital in North India. Dr. Kler is a genius.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1988, isFeatured: true,
  },

  // ── BANGALORE ───────────────────────────────────────────────────
  {
    name: 'Narayana Hrudayalaya (NH) Heart Institute Bangalore',
    type: 'private', tier: 'mid',
    address: '258/A Bommasandra Industrial Area, Anekal Taluk, Bangalore - 560099',
    city: 'Bangalore', state: 'Karnataka', pincode: '560099',
    location: { type: 'Point', coordinates: [77.6610, 12.8166] },
    phone: ['+91-80-71222222'],
    accreditations: ['NABH','JCI','NABL','PMJAY'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Cardiac Surgery','Pediatric Cardiology','Telemedicine'],
    procedures: ['angioplasty','bypass_surgery','angiography','cataract_surgery'],
    totalBeds: 1000, icuBeds: 150, emergency: true, opd: true,
    rating: 4.7, reviewCount: 6820, procedureVolume: 'very_high',
    scores: { clinical: 96, reputation: 93, accessibility: 72, affordability: 78, overall: 89 },
    costRanges: {
      angioplasty:      { low: 160000, high: 280000 },
      bypass_surgery:   { low: 280000, high: 480000 },
      angiography:      { low: 14000,  high: 28000  },
    },
    doctors: [
      { name: 'Dr. Devi Prasad Shetty', specialty: 'Founder, Cardiac Surgeon', experience: 40, rating: 5.0, consultationFee: 2000 },
      { name: 'Dr. Sathyamurthy', specialty: 'Senior Interventional Cardiologist', experience: 28, rating: 4.8, consultationFee: 1500 },
    ],
    reviews: [
      { author: 'Kiran Kumar', rating: 5, text: 'Affordable cardiac care without compromising on quality. Revolutionary model.', verified: true },
      { author: 'Meera Reddy', rating: 5, text: 'Dr. Devi Shetty is a legend. Best value cardiac hospital in India.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 2000, isFeatured: true,
  },
  {
    name: 'Manipal Hospital (Old Airport Road)',
    type: 'private', tier: 'premium',
    address: '98, HAL Airport Road, Bangalore - 560017',
    city: 'Bangalore', state: 'Karnataka', pincode: '560017',
    location: { type: 'Point', coordinates: [77.6474, 12.9592] },
    phone: ['+91-80-25023344'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Oncology','Transplant','Neurology','Orthopedics','Dermatology'],
    procedures: ['angioplasty','bypass_surgery','kidney_transplant','chemotherapy','knee_replacement','neurosurgery'],
    totalBeds: 600, icuBeds: 100, emergency: true, opd: true,
    rating: 4.6, reviewCount: 4120, procedureVolume: 'very_high',
    scores: { clinical: 95, reputation: 92, accessibility: 74, affordability: 55, overall: 87 },
    costRanges: {
      angioplasty:      { low: 220000, high: 380000 },
      bypass_surgery:   { low: 420000, high: 720000 },
      kidney_transplant:{ low: 600000, high: 1100000},
      knee_replacement: { low: 200000, high: 360000 },
    },
    doctors: [
      { name: 'Dr. Suresh Rao', specialty: 'Chairman Cardiology', experience: 28, rating: 4.8, consultationFee: 2000 },
      { name: 'Dr. Sachin Patil', specialty: 'Transplant Surgeon', experience: 22, rating: 4.7, consultationFee: 1800 },
    ],
    reviews: [
      { author: 'Narayana Murthy', rating: 5, text: 'World-class facility in Bangalore. My cancer surgery went perfectly.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1991,
  },

  // ── HYDERABAD ───────────────────────────────────────────────────
  {
    name: 'KIMS Hospitals Secunderabad',
    type: 'private', tier: 'mid',
    address: '1-8-31/1, Minister Road, Secunderabad, Hyderabad - 500003',
    city: 'Hyderabad', state: 'Telangana', pincode: '500003',
    location: { type: 'Point', coordinates: [78.4989, 17.4401] },
    phone: ['+91-40-44885000'],
    accreditations: ['NABH','NABL','PMJAY'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Orthopedics','Oncology','Neurology','Nephrology','Urology'],
    procedures: ['angioplasty','knee_replacement','hip_replacement','dialysis','chemotherapy','neurosurgery'],
    totalBeds: 250, icuBeds: 42, emergency: true, opd: true,
    rating: 4.3, reviewCount: 1980, procedureVolume: 'medium',
    scores: { clinical: 83, reputation: 80, accessibility: 88, affordability: 80, overall: 83 },
    costRanges: {
      angioplasty:      { low: 145000, high: 265000 },
      knee_replacement: { low: 155000, high: 285000 },
      dialysis:         { low: 1200,   high: 2800   },
    },
    doctors: [
      { name: 'Dr. Ravi Kiran', specialty: 'Cardiologist', experience: 17, rating: 4.5, consultationFee: 800 },
      { name: 'Dr. Laxmi Devi', specialty: 'Orthopedic Surgeon', experience: 14, rating: 4.4, consultationFee: 700 },
    ],
    reviews: [
      { author: 'Raju Prasad', rating: 4, text: 'Good hospital with PM-JAY facility. Reasonable pricing for Hyderabad.', verified: true },
    ],
    dataSource: 'pmjay', establishedYear: 2000,
  },
  {
    name: 'Apollo Hospitals Jubilee Hills Hyderabad',
    type: 'private', tier: 'premium',
    address: 'Film Nagar, Jubilee Hills, Hyderabad - 500033',
    city: 'Hyderabad', state: 'Telangana', pincode: '500033',
    location: { type: 'Point', coordinates: [78.4088, 17.4271] },
    phone: ['+91-40-23607777'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Oncology','Neurology','Transplant','Orthopedics'],
    procedures: ['angioplasty','bypass_surgery','chemotherapy','neurosurgery','knee_replacement','kidney_transplant'],
    totalBeds: 550, icuBeds: 90, emergency: true, opd: true,
    rating: 4.5, reviewCount: 3280, procedureVolume: 'high',
    scores: { clinical: 92, reputation: 89, accessibility: 72, affordability: 50, overall: 84 },
    costRanges: {
      angioplasty:      { low: 210000, high: 370000 },
      bypass_surgery:   { low: 400000, high: 700000 },
      knee_replacement: { low: 185000, high: 330000 },
    },
    doctors: [
      { name: 'Dr. Hari Prasad', specialty: 'Senior Cardiologist', experience: 24, rating: 4.7, consultationFee: 1800 },
    ],
    reviews: [
      { author: 'Srinivas Reddy', rating: 5, text: 'Apollo quality with Hyderabad convenience. Excellent facilities.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1988, isFeatured: true,
  },

  // ── PUNE ────────────────────────────────────────────────────────
  {
    name: 'Ruby Hall Clinic Pune',
    type: 'private', tier: 'premium',
    address: '40, Sassoon Road, Pune - 411001',
    city: 'Pune', state: 'Maharashtra', pincode: '411001',
    location: { type: 'Point', coordinates: [73.8767, 18.5314] },
    phone: ['+91-20-66455000'],
    accreditations: ['NABH','NABL'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Oncology','Orthopedics','Neurology','Gynecology','Neonatology'],
    procedures: ['angioplasty','bypass_surgery','knee_replacement','chemotherapy','neurosurgery','normal_delivery','c_section'],
    totalBeds: 400, icuBeds: 72, emergency: true, opd: true,
    rating: 4.5, reviewCount: 3040, procedureVolume: 'high',
    scores: { clinical: 91, reputation: 88, accessibility: 80, affordability: 62, overall: 86 },
    costRanges: {
      angioplasty:      { low: 195000, high: 340000 },
      bypass_surgery:   { low: 380000, high: 660000 },
      knee_replacement: { low: 175000, high: 310000 },
      normal_delivery:  { low: 18000,  high: 45000  },
      c_section:        { low: 45000,  high: 90000  },
    },
    doctors: [
      { name: 'Dr. Pradeep Gadge', specialty: 'Senior Cardiologist', experience: 25, rating: 4.8, consultationFee: 1500 },
      { name: 'Dr. Smita Joshi', specialty: 'Gynecologist & Obstetrician', experience: 20, rating: 4.7, consultationFee: 1200 },
    ],
    reviews: [
      { author: 'Ashish Deshmukh', rating: 5, text: "Pune's finest hospital. Outstanding cardiology department.", verified: true },
      { author: 'Sonali Patil', rating: 4, text: 'Had my C-section here. Clean facilities and caring staff.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1959,
  },

  // ── CHENNAI ─────────────────────────────────────────────────────
  {
    name: 'Apollo Hospitals Greams Road Chennai',
    type: 'private', tier: 'super_premium',
    address: '21, Greams Lane, Off Greams Road, Chennai - 600006',
    city: 'Chennai', state: 'Tamil Nadu', pincode: '600006',
    location: { type: 'Point', coordinates: [80.2564, 13.0581] },
    phone: ['+91-44-28290200'],
    accreditations: ['NABH','JCI','NABL'], pmjayEmpanelled: false,
    specializations: ['Cardiology','Oncology','Transplant','Neurology','Orthopedics','Spine'],
    procedures: ['angioplasty','bypass_surgery','chemotherapy','kidney_transplant','knee_replacement','neurosurgery'],
    totalBeds: 700, icuBeds: 115, emergency: true, opd: true,
    rating: 4.7, reviewCount: 7420, procedureVolume: 'very_high',
    scores: { clinical: 97, reputation: 95, accessibility: 68, affordability: 35, overall: 89 },
    costRanges: {
      angioplasty:      { low: 240000, high: 420000 },
      bypass_surgery:   { low: 460000, high: 800000 },
      kidney_transplant:{ low: 650000, high: 1200000},
    },
    doctors: [
      { name: 'Dr. K. M. Cherian', specialty: 'Legendary Cardiac Surgeon', experience: 45, rating: 5.0, consultationFee: 5000 },
    ],
    reviews: [
      { author: 'P. Chidambaram', rating: 5, text: 'Apollo Chennai is where Indian medical excellence was born. Simply the best.', verified: true },
    ],
    dataSource: 'nabh', establishedYear: 1983, isFeatured: true,
  },

  // ── JAIPUR ──────────────────────────────────────────────────────
  {
    name: 'SMS Medical College & Hospital Jaipur',
    type: 'public', tier: 'government',
    address: 'JLN Marg, Jaipur - 302004',
    city: 'Jaipur', state: 'Rajasthan', pincode: '302004',
    location: { type: 'Point', coordinates: [75.7931, 26.9021] },
    phone: ['+91-141-2518501'],
    accreditations: ['NABH','PMJAY','CGHS'], pmjayEmpanelled: true,
    specializations: ['All Specializations','Cardiology','Neurology','Trauma','Burns'],
    procedures: ['angioplasty','bypass_surgery','dialysis','chemotherapy','neurosurgery','appendectomy','normal_delivery'],
    totalBeds: 3000, icuBeds: 250, emergency: true, opd: true,
    rating: 3.8, reviewCount: 9820, procedureVolume: 'very_high',
    scores: { clinical: 80, reputation: 75, accessibility: 94, affordability: 98, overall: 84 },
    costRanges: {
      angioplasty:      { low: 35000,  high: 80000  },
      bypass_surgery:   { low: 75000,  high: 150000 },
      dialysis:         { low: 700,    high: 1600   },
    },
    doctors: [
      { name: 'Dr. Ashok Gupta', specialty: 'Professor Cardiology', experience: 28, rating: 4.4, consultationFee: 150 },
    ],
    reviews: [
      { author: 'Ramji Lal Meena', rating: 4, text: 'Free treatment under Chiranjeevi scheme. Doctors are knowledgeable.', verified: false },
    ],
    dataSource: 'pmjay', establishedYear: 1947,
  },
  {
    name: 'Mahatma Gandhi Medical College & Hospital Jaipur',
    type: 'private', tier: 'mid',
    address: 'RIICO Institutional Area, Sitapura, Jaipur - 302022',
    city: 'Jaipur', state: 'Rajasthan', pincode: '302022',
    location: { type: 'Point', coordinates: [75.8620, 26.7972] },
    phone: ['+91-141-5190000'],
    accreditations: ['NABH','NABL','PMJAY'], pmjayEmpanelled: true,
    specializations: ['Cardiology','Orthopedics','Oncology','Nephrology','Gastroenterology'],
    procedures: ['angioplasty','knee_replacement','dialysis','chemotherapy','appendectomy','normal_delivery','c_section'],
    totalBeds: 1500, icuBeds: 100, emergency: true, opd: true,
    rating: 4.2, reviewCount: 2140, procedureVolume: 'high',
    scores: { clinical: 84, reputation: 80, accessibility: 82, affordability: 76, overall: 81 },
    costRanges: {
      angioplasty:      { low: 130000, high: 240000 },
      knee_replacement: { low: 120000, high: 220000 },
      dialysis:         { low: 1000,   high: 2200   },
    },
    doctors: [
      { name: 'Dr. Rohit Sharma', specialty: 'Cardiologist', experience: 16, rating: 4.4, consultationFee: 600 },
    ],
    reviews: [
      { author: 'Deepak Mathur', rating: 4, text: 'Good hospital in Jaipur. Affordable prices. PM-JAY accepted.', verified: true },
    ],
    dataSource: 'pmjay', establishedYear: 2002,
  },
];

// ─── City pricing index — referenced from CGHS rate zones ────────
const CITY_PRICING = {
  'Mumbai':    { multiplier: 1.00, tier: 1, cghsZone: 'Z1' },
  'Delhi':     { multiplier: 0.96, tier: 1, cghsZone: 'Z1' },
  'Bangalore': { multiplier: 0.93, tier: 1, cghsZone: 'Z2' },
  'Chennai':   { multiplier: 0.88, tier: 1, cghsZone: 'Z2' },
  'Hyderabad': { multiplier: 0.84, tier: 2, cghsZone: 'Z2' },
  'Pune':      { multiplier: 0.88, tier: 1, cghsZone: 'Z2' },
  'Kolkata':   { multiplier: 0.82, tier: 1, cghsZone: 'Z2' },
  'Nagpur':    { multiplier: 0.78, tier: 2, cghsZone: 'Z3' },
  'Ahmedabad': { multiplier: 0.80, tier: 2, cghsZone: 'Z3' },
  'Jaipur':    { multiplier: 0.74, tier: 2, cghsZone: 'Z3' },
  'Lucknow':   { multiplier: 0.70, tier: 2, cghsZone: 'Z3' },
  'Bhopal':    { multiplier: 0.68, tier: 2, cghsZone: 'Z3' },
  'Indore':    { multiplier: 0.70, tier: 2, cghsZone: 'Z3' },
  'Chandigarh':{ multiplier: 0.76, tier: 2, cghsZone: 'Z3' },
  'Patna':     { multiplier: 0.62, tier: 3, cghsZone: 'Z4' },
  'Ranchi':    { multiplier: 0.60, tier: 3, cghsZone: 'Z4' },
  'Raipur':    { multiplier: 0.63, tier: 3, cghsZone: 'Z4' },
  'Aurangabad':{ multiplier: 0.68, tier: 2, cghsZone: 'Z3' },
  'Vadodara':  { multiplier: 0.72, tier: 2, cghsZone: 'Z3' },
  'Visakhapatnam': { multiplier: 0.72, tier: 2, cghsZone: 'Z3' },
};

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 5000 });
    console.log('✅ Connected to MongoDB for seeding');
  } catch (e) {
    console.error('⚠️  MongoDB unavailable — seeding skipped:', e.message);
    process.exit(0);
  }

  // Clear
  await Promise.all([User.deleteMany({}), Hospital.deleteMany({}), Procedure.deleteMany({})]);
  console.log('🗑️  Cleared existing data');

  // Admin user
  const admin = await User.create({
    name: process.env.ADMIN_NAME || 'MedIQ Admin',
    email: process.env.ADMIN_EMAIL || 'admin@mediq.ai',
    password: process.env.ADMIN_PASSWORD || 'Admin@MedIQ2026',
    role: 'admin',
    isActive: true,
    isEmailVerified: true,
  });
  console.log(`👤 Admin created: ${admin.email}`);

  // Demo customers
  const customers = await User.create([
    { name: 'Rahul Sharma', email: 'rahul@demo.com', password: 'Demo@1234', role: 'customer',
      profile: { age: 58, city: 'Nagpur', comorbidities: ['diabetes','hypertension'] } },
    { name: 'Priya Nair',   email: 'priya@demo.com', password: 'Demo@1234', role: 'customer',
      profile: { age: 34, city: 'Mumbai' } },
  ]);
  console.log(`👥 ${customers.length} demo customers created`);

  // Procedures
  const procs = await Procedure.insertMany(PROCEDURE_SEED.map(p => ({
    ...p,
    comorbidityRisk: p.comorbidityRisk ? new Map(Object.entries(p.comorbidityRisk)) : undefined,
  })));
  console.log(`💊 ${procs.length} procedures seeded (PM-JAY HBP aligned)`);

  // Hospitals
  const hosps = await Hospital.insertMany(HOSPITAL_SEED.map(h => ({
    ...h,
    costRanges: h.costRanges ? new Map(Object.entries(h.costRanges)) : undefined,
    slug: h.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '-' + Date.now(),
  })));
  console.log(`🏥 ${hosps.length} hospitals seeded (NABH/PM-JAY sourced)`);

  console.log('\n╔══════════════════════════════════════════════════════╗');
  console.log('║  ✅  Database seeded successfully!                   ║');
  console.log('║                                                      ║');
  console.log(`║  Admin:     ${process.env.ADMIN_EMAIL || 'admin@mediq.ai'} / Admin@MedIQ2026  ║`);
  console.log('║  Customer:  rahul@demo.com / Demo@1234               ║');
  console.log('║  Customer:  priya@demo.com / Demo@1234               ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
